import React from "react";

const sizeClasses = {
  txtGilroySemiBold24: "font-gilroy font-semibold",
  txtGilroySemiBold16Black90001: "font-gilroy font-semibold",
  txtGilroySemiBold20: "font-gilroy font-semibold",
  txtGilroyMedium12BlueA700: "font-gilroy font-medium",
  txtGilroyBold36: "font-bold font-gilroy",
  txtGilroySemiBold16WhiteA700: "font-gilroy font-semibold",
  txtGilroySemiBold16Gray90002: "font-gilroy font-semibold",
  txtGilroySemiBold12Gray5001: "font-gilroy font-semibold",
  txtGilroySemiBold24Black90001: "font-gilroy font-semibold",
  txtGilroySemiBold28: "font-gilroy font-semibold",
  txtGilroyBold36Red700: "font-bold font-gilroy",
  txtGilroyMedium16Gray900: "font-gilroy font-medium",
  txtGilroyMedium16BlueA700: "font-gilroy font-medium",
  txtGilroyRegular14Bluegray900: "font-gilroy font-normal",
  txtGilroyRegular18: "font-gilroy font-normal",
  txtOpenSansMedium14: "font-medium font-opensans",
  txtGilroySemiBold18Bluegray900: "font-gilroy font-semibold",
  txtGilroySemiBold24Black900: "font-gilroy font-semibold",
  txtGilroyMedium18Black90002: "font-gilroy font-medium",
  txtGilroyMedium14BlueA700: "font-gilroy font-medium",
  txtGilroyMedium18Black90001: "font-gilroy font-medium",
  txtGilroyBold28: "font-bold font-gilroy",
  txtGilroySemiBold32: "font-gilroy font-semibold",
  txtGilroySemiBold18Black900: "font-gilroy font-semibold",
  txtGilroyBold20: "font-bold font-gilroy",
  txtGilroyRegular16Black90001: "font-gilroy font-normal",
  txtGilroyMedium16Black90001: "font-gilroy font-medium",
  txtGilroyMedium16Bluegray900: "font-gilroy font-medium",
  txtGilroyRegular16Bluegray900: "font-gilroy font-normal",
  txtGilroySemiBold16Green600: "font-gilroy font-semibold",
  txtGilroySemiBold36: "font-gilroy font-semibold",
  txtGilroyMedium18Bluegray900: "font-gilroy font-medium",
  txtGilroyRegular16Bluegray90001: "font-gilroy font-normal",
  txtGilroySemiBold16Gray90004: "font-gilroy font-semibold",
  txtGilroyMedium14Gray40001: "font-gilroy font-medium",
  txtRobotoMedium10: "font-medium font-roboto",
  txtGilroySemiBold16BlueA700: "font-gilroy font-semibold",
  txtInterRegular14: "font-inter font-normal",
  txtGilroyBold36WhiteA700: "font-bold font-gilroy",
  txtGilroySemiBold18Gray50: "font-gilroy font-semibold",
  txtGilroyMedium16Red700: "font-gilroy font-medium",
  txtGilroyBold18: "font-bold font-gilroy",
  txtGilroyMedium18Black900: "font-gilroy font-medium",
  txtGilroySemiBold16Red700: "font-gilroy font-semibold",
  txtGilroyRegular14WhiteA700: "font-gilroy font-normal",
  txtGilroyMedium20: "font-gilroy font-medium",
  txtGilroyMedium18Green600: "font-gilroy font-medium",
  txtGilroySemiBold18Black90001: "font-gilroy font-semibold",
  txtGilroyMedium24: "font-gilroy font-medium",
  txtGilroyMedium24Bluegray900: "font-gilroy font-medium",
  txtGilroyBold36Green600: "font-bold font-gilroy",
  txtGilroySemiBold14Bluegray700: "font-gilroy font-semibold",
  txtGilroyMedium16Bluegray600: "font-gilroy font-medium",
  txtGilroyMedium24Black90001: "font-gilroy font-medium",
  txtPoppinsRegular12: "font-normal font-poppins",
  txtGilroySemiBold32Gray50: "font-gilroy font-semibold",
  txtGilroySemiBold24BlueA700: "font-gilroy font-semibold",
  txtGilroyMedium16Bluegray200: "font-gilroy font-medium",
  txtGilroySemiBold14Bluegray900: "font-gilroy font-semibold",
  txtGilroyRegular14Bluegray400: "font-gilroy font-normal",
  txtGilroyMedium12WhiteA700: "font-gilroy font-medium",
  txtGilroySemiBold14Black90001: "font-gilroy font-semibold",
  txtGilroyMedium16Green600: "font-gilroy font-medium",
  txtGilroyMedium14Black900: "font-gilroy font-medium",
  txtGilroyMedium14Black90001: "font-gilroy font-medium",
  txtGilroySemiBold12: "font-gilroy font-semibold",
  txtGilroyMedium20Black90001: "font-gilroy font-medium",
  txtOpenSansRomanSemiBold16: "font-opensans font-semibold",
  txtGilroySemiBold10: "font-gilroy font-semibold",
  txtGilroyMedium20Black90002: "font-gilroy font-medium",
  txtMontserratMedium14: "font-medium font-montserrat",
  txtGilroySemiBold32Black900: "font-gilroy font-semibold",
  txtGilroyRegular16Bluegray200: "font-gilroy font-normal",
  txtGilroyMedium14: "font-gilroy font-medium",
  txtGilroyMedium18BlueA700: "font-gilroy font-medium",
  txtGilroyMedium12: "font-gilroy font-medium",
  txtGilroySemiBold18: "font-gilroy font-semibold",
  txtGilroyMedium18: "font-gilroy font-medium",
  txtGilroySemiBold16: "font-gilroy font-semibold",
  txtGilroyRegular16: "font-gilroy font-normal",
  txtGilroyMedium16: "font-gilroy font-medium",
  txtOpenSansRomanSemiBold12: "font-opensans font-semibold",
  txtGilroyRegular14: "font-gilroy font-normal",
  txtGilroySemiBold14: "font-gilroy font-semibold",
  txtGilroyBold18Red700: "font-bold font-gilroy",
  txtGilroySemiBold16Bluegray700: "font-gilroy font-semibold",
  txtGilroySemiBold16Bluegray900: "font-gilroy font-semibold",
  txtGilroyMedium14Red700: "font-gilroy font-medium",
  txtGilroySemiBold18Gray90005: "font-gilroy font-semibold",
  txtGilroySemiBold18Gray90003: "font-gilroy font-semibold",
  txtGilroyMedium16WhiteA700: "font-gilroy font-medium",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
